---
- name: Patch Linux system
  hosts: node1
  remote_user: ansible
  become: true
        
  tasks:
    - name: Check RHN or local repository connectivity
      shell:  yum repolist  > /dev/null 2>&1; if [ $? -eq 0 ]; then echo "Repository Configured"; else echo "No valid repository"; fi
      register: repo_status
                      
    - name: Failed if no repository found
      debug:
        msg: "{{ inventory_hostname }} doesnot have repository configured"
      when: repo_status.stdout == No valid repository
      ignore_errors: yes
      
    - name: Check Apache is running or not
      shell: systemctl status httpd >/dev/null 2>&1; if [ $? -eq 0 ]; then echo 'httpd is running'; else echo 'httpd is not running'; fi
      register: apache_status
                                                                                
    - name: Failed if Apache is running
      debug:
        msg: "{{ inventory_hostname }} running apache application"
      when: apache_status.stdout == httpd is running
      ignore_errors: yes
                                                                                         
    - name: Apply patch on the system
      shell: yum update -y
      when: apache_status.stdout == httpd is not running and repo_status.stdout == Repository Configured
  
